# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=5000)),
                ('title', models.CharField(max_length=150)),
                ('sub_title', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.FileField(blank=True, default='static/img/default_post.jpg', upload_to='static/img')),
                ('published_on', models.DateTimeField(verbose_name='date_published')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
